-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.migrations
(
    id serial NOT NULL,
    "timestamp" bigint NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.nofitications
(
    id serial NOT NULL,
    title character varying COLLATE pg_catalog."default" NOT NULL,
    content character varying COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL,
    "createdById" integer,
    CONSTRAINT "PK_502a8728498d5e9bae4d1b93519" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."nofitications-user"
(
    id serial NOT NULL,
    is_read boolean NOT NULL,
    "userId" integer,
    "notificationId" integer,
    CONSTRAINT "PK_5b6d6f50bcef0280dd3855d03b7" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles_users_projects
(
    id serial NOT NULL,
    "userId" integer,
    "roleId" integer,
    "projectId" integer,
    CONSTRAINT "PK_a595613d866fc26960169338c85" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.task_user
(
    id serial NOT NULL,
    "userId" integer,
    "taskId" integer,
    CONSTRAINT "PK_6ea2c1c13f01b7a383ebbeaebb0" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tasks
(
    id serial NOT NULL,
    project_id integer NOT NULL,
    task_description character varying COLLATE pg_catalog."default" NOT NULL,
    task_state character varying COLLATE pg_catalog."default" NOT NULL,
    task_priority character varying COLLATE pg_catalog."default" NOT NULL,
    task_name character varying COLLATE pg_catalog."default" NOT NULL,
    created_time timestamp without time zone NOT NULL,
    task_deadline timestamp without time zone NOT NULL,
    done_at timestamp without time zone NOT NULL,
    "projectId" integer,
    "createdById" integer,
    CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    noti_settings boolean NOT NULL DEFAULT true,
    is_banned boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.nofitications
    ADD CONSTRAINT "FK_a5293f4060e358e18923d8d127f" FOREIGN KEY ("createdById")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."nofitications-user"
    ADD CONSTRAINT "FK_727b925882b5f841ab4a86fa995" FOREIGN KEY ("userId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."nofitications-user"
    ADD CONSTRAINT "FK_cf8de016e471f03a06b80470c5e" FOREIGN KEY ("notificationId")
    REFERENCES public.nofitications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.roles_users_projects
    ADD CONSTRAINT "FK_a5dbc89430a891057373d445f34" FOREIGN KEY ("projectId")
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.roles_users_projects
    ADD CONSTRAINT "FK_ace5fe88d0950333206ceecc80c" FOREIGN KEY ("roleId")
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.roles_users_projects
    ADD CONSTRAINT "FK_db4144a24108a3835a4bf540357" FOREIGN KEY ("userId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.task_user
    ADD CONSTRAINT "FK_0f500c19a4a119f22a82c9b3640" FOREIGN KEY ("userId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.task_user
    ADD CONSTRAINT "FK_ff099dc6756bfef736ebe18ea9a" FOREIGN KEY ("taskId")
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT "FK_660898d912c6e71107e9ef8f38d" FOREIGN KEY ("createdById")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956" FOREIGN KEY ("projectId")
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;